version: '3.8'

services:
  grafica-express:
    image: ghcr.io/cristhian-sancore/graficarapida:latest
    container_name: grafica_rapida_portainer
    restart: always
    ports:
      - "8050:8050"
    environment:
      - PORT=8050
      - FLASK_ENV=production
      - DB_PATH=/app/data/grafica.db
    volumes:
      - grafica_db_data:/app/data
      - grafica_uploads_data:/app/static/uploads

volumes:
  grafica_db_data:
    driver: local
  grafica_uploads_data:
    driver: local
