version: '3.8'

services:
  grafica-web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: grafica_rapida_app
    restart: unless-stopped
    ports:
      - "8050:8050"
    volumes:
      - ./grafica.db:/app/grafica.db
      - ./static/uploads:/app/static/uploads
    environment:
      - PORT=8050
      - FLASK_ENV=production
