version: '3.8'

services:
  # BANCO DE DADOS POSTGRESQL (Alta Performance & Produção)
  postgres-db:
    image: postgres:15-alpine
    container_name: grafica_postgres
    restart: always
    environment:
      POSTGRES_DB: graficadb
      POSTGRES_USER: graficauser
      POSTGRES_PASSWORD: graficapassword2026
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U graficauser -d graficadb"]
      interval: 5s
      timeout: 5s
      retries: 5

  # APLICAÇÃO WEB DA GRÁFICA RÁPIDA
  grafica-express:
    image: ghcr.io/cristhian-sancore/graficarapida:latest
    container_name: grafica_rapida_portainer
    restart: always
    ports:
      - "8050:8050"
    environment:
      - PORT=8050
      - FLASK_ENV=production
      - DATABASE_URL=postgresql://graficauser:graficapassword2026@postgres-db:5432/graficadb
    depends_on:
      postgres-db:
        condition: service_healthy
    volumes:
      - grafica_uploads_data:/app/static/uploads

volumes:
  postgres_data:
    driver: local
  grafica_uploads_data:
    driver: local
