version: '3.8'

services:
  grafica-web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: grafica_rapida_app
    restart: unless-stopped
    ports:
      - "8050:8050"
    volumes:
      - grafica_db_data:/app/data
      - grafica_uploads_data:/app/static/uploads
    environment:
      - PORT=8050
      - FLASK_ENV=production
      - DB_PATH=/app/data/grafica.db

volumes:
  grafica_db_data:
    driver: local
  grafica_uploads_data:
    driver: local
